server:
  port: 9527

spring:
  application:
    name: springcloud-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: zuul9527
    prefer-ip-address: true
info:
  app.name: qqqzuul
  company.name: 啥玩意儿


zuul:
  routes:
   mydept.serviceId: springcloud-provider-dept
   mydept.path: /mydept/**
  ignored-services: springcloud-provider-dept # 不能使用这个微服务ID进行访问  “ * ” 隐藏全部的
#  ignored-services: "*"                      # 不能使用这个微服务ID进行访问  “ * ” 隐藏全部的
  prefix: /qqq #设置公共的前缀   #最终可以访问的url  http://localhost:9527/qqq/mydept/dept/get/1
