server:
  port: 7001


# Eureka
eureka:
  instance:
    hostname: localhost #Eureka 服务端得实例名称
  client:
    register-with-eureka: false # 是否允许将违微服务注册到eureka  false：否 true 是
    fetch-registry: false # 如果fetch-registry为false，则表示自己为注册中心
    service-url:  #监控页面
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/